cc_test(
    name = "string_helper_test",
    srcs = ["string_helper_test.cpp"],
    deps = [
        "//utils:string_helper",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        ],

)